name: Deploy RealState API and Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build et push pour realstate-api
      - name: Build and push RealState API Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/realstate-api:latest

      # Build et push pour realstate-frontend
      - name: Build and push RealState Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./realstate-frontend
          file: ./realstate-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/realstate-frontend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Créer un réseau Docker s'il n'existe pas
            docker network create xtracto-network || true

            # Vérifier si mongodb existe et le connecter au réseau
            if [ "$(docker ps -q -f name=mongodb)" ]; then
              echo "Conteneur mongodb en cours d'exécution, connexion au réseau..."
              docker network connect xtracto-network mongodb || true
            else
              echo "Conteneur mongodb non trouvé, démarrage d'une nouvelle instance..."
              docker run -d \
                --name mongodb \
                -p 27017:27017 \
                -e MONGO_INITDB_ROOT_USERNAME=admin \
                -e MONGO_INITDB_ROOT_PASSWORD=SuperSecureP@ssw0rd! \
                --network xtracto-network \
                mongodb/mongodb-community-server:latest
            fi

            # Déployer realstate-api
            if [ "$(docker ps -q -f name=realstate-api)" ]; then
              docker stop realstate-api
              docker rm realstate-api
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/realstate-api:latest
            docker run -d \
              --name realstate-api \
              -p 5009:5009 \
              --env-file /home/ubuntu/realstate-api/.env \
              --network xtracto-network \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/realstate-api:latest

            # Déployer realstate-frontend
            if [ "$(docker ps -q -f name=realstate-frontend)" ]; then
              docker stop realstate-frontend
              docker rm realstate-frontend
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/realstate-frontend:latest
            docker run -d \
              --name realstate-frontend \
              -p 80:80 \
              --network xtracto-network \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/realstate-frontend:latest

            echo "Deployed successfully"